#!/bin/bash

CMD="ctags-exuberant -e -R --extra=q "
input=$1

if [ -a $(pwd)/.utagcmd ]
then
	echo "Reading new CMD from .utagcmd"
	CMD=$(cat $(pwd)/.utagcmd)
	echo "  CMD = ${CMD}"
	eval $CMD
elif [ -n "$input" ]
then
    echo "Generating tags table using exuberant ctags with given directories/files"
    ${CMD} $@
else
    echo "Generating tags table by searching in the following directory:"
    echo "    " `pwd` 
    echo
    find . -regex ".*\.[cChH]\(pp\)?\|.*\.py" -print | cut -c3- | ${CMD}
fi
dir=$(pwd)
localcontent="((nil . ((tags-file-name . \"${dir}/TAGS\")
(tags-table-list . (\"${dir}/TAGS\")))))"
echo ${localcontent} > .dir-locals.el
