#!/bin/bash

if [ $# -eq 0 ]; then
  echo usage: $(basename $0) "on|off"
  exit 1
fi


if [ $1 = "off" ]; then
    echo  "Turning monitor off"
    xrandr --output CRT1 --off
elif [ $1 = "on" ]; then
    echo "Turning Monitor on"
    xrandr --output CRT1 --auto --right-of LVDS
else
    echo usage: $(basename $0) "on|off"
fi
